# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cow', '0003_auto_20170305_0305'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePlugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='images')),
            ],
        ),
    ]
