# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 20:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cow', '0004_imageplugin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='content',
        ),
    ]
