# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 03:02
from __future__ import unicode_literals

from django.db import migrations, models
import sorl.thumbnail.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('cow', '0005_remove_page_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressplugin',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='imageplugin',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='textplugin',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
